server:
  port: 8001
spring:
  rabbitmq:
    username: guest
    password: guest
    host: 127.0.0.1
    port: 5672
#  application:
#    name: procument
#eureka:
#  client:
#    service-url:
#      defaultZone: http://localhost:8040/eureka/
